# Generated by Django 3.0.3 on 2020-03-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200303_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='bio',
            field=models.TextField(max_length=800),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
