# Generated by Django 3.0.3 on 2020-02-27 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20200227_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='city',
            new_name='local_area',
        ),
    ]
