# Generated by Django 3.0.3 on 2020-02-28 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0003_auto_20200227_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='image',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='trip',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL),
        ),
    ]
