# Generated by Django 3.0.3 on 2020-03-02 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_auto_20200228_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='cost_currency',
        ),
        migrations.AlterField(
            model_name='trip',
            name='cost',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='country',
            field=models.CharField(max_length=150),
        ),
    ]
