# Generated by Django 3.0.3 on 2020-03-03 21:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_auto_20200302_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='Length',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
